/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import Avatar.AvatarPanel;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.BorderLayout;
import javax.swing.UIManager;

/**
 *
 * @author zoeca
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        setContentPane(new FondoCircuitosPanel());
        initComponents();
        panelAvatar.setOpaque(false);
        PanelRegistrar.putClientProperty("FlatLaf.style",
        "arc:35");
        configurarVentana();
        configurarPaneles();
        configurarComponentesFlatLaf();
        cargarAvatar();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelRegistrar = new PanelSombra();
        lblRegistrate = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblSeccion = new javax.swing.JLabel();
        txfNombre = new javax.swing.JTextField();
        cmbSeccion = new javax.swing.JComboBox<>();
        btnComenzar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        panelAvatar = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelRegistrar.setBackground(new java.awt.Color(199, 232, 253));

        lblRegistrate.setBackground(new java.awt.Color(1, 83, 137));
        lblRegistrate.setFont(new java.awt.Font("Pixel Digivolve", 1, 54)); // NOI18N
        lblRegistrate.setForeground(new java.awt.Color(1, 83, 137));
        lblRegistrate.setText("¡Registrate!");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 55, 93));
        lblNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosL/person (1).png"))); // NOI18N
        lblNombre.setText("Escribe Tu Nombre:");

        lblSeccion.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblSeccion.setForeground(new java.awt.Color(0, 55, 93));
        lblSeccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosL/info (1).png"))); // NOI18N
        lblSeccion.setText("Grado y Sección:");

        txfNombre.addActionListener(this::txfNombreActionPerformed);

        cmbSeccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbSeccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona tu Sección:", "Noveno 1", "Noveno 2", "Noveno 3", "Noveno 4", "Noveno 5", "Noveno 6", "Noveno 7" }));

        btnComenzar.setBackground(new java.awt.Color(1, 121, 115));
        btnComenzar.setFont(new java.awt.Font("Pixel Digivolve", 1, 24)); // NOI18N
        btnComenzar.setForeground(new java.awt.Color(255, 255, 255));
        btnComenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosL/play.png"))); // NOI18N
        btnComenzar.setText("Comenzar a Jugar");
        btnComenzar.addActionListener(this::btnComenzarActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(96, 133, 158));
        jLabel2.setText("Prepárate para descubrir si eres un Bit o un Bot");

        javax.swing.GroupLayout PanelRegistrarLayout = new javax.swing.GroupLayout(PanelRegistrar);
        PanelRegistrar.setLayout(PanelRegistrarLayout);
        PanelRegistrarLayout.setHorizontalGroup(
            PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistrarLayout.createSequentialGroup()
                .addGap(0, 106, Short.MAX_VALUE)
                .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
            .addGroup(PanelRegistrarLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(lblSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistrarLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistrarLayout.createSequentialGroup()
                        .addComponent(lblRegistrate)
                        .addGap(153, 153, 153))))
        );
        PanelRegistrarLayout.setVerticalGroup(
            PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistrarLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblRegistrate)
                .addGap(48, 48, 48)
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(lblSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btnComenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        panelAvatar.setBackground(new java.awt.Color(153, 204, 255));
        panelAvatar.setForeground(new java.awt.Color(38, 105, 145));

        javax.swing.GroupLayout panelAvatarLayout = new javax.swing.GroupLayout(panelAvatar);
        panelAvatar.setLayout(panelAvatarLayout);
        panelAvatarLayout.setHorizontalGroup(
            panelAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );
        panelAvatarLayout.setVerticalGroup(
            panelAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
        );

        lblTitulo.setFont(new java.awt.Font("Pixel Digivolve", 1, 130)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 66, 119));
        lblTitulo.setText("BITS");

        lblTitulo1.setFont(new java.awt.Font("Pixel Digivolve", 1, 70)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(0, 66, 119));
        lblTitulo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosL/computer-mouse.png"))); // NOI18N

        lblTitulo2.setFont(new java.awt.Font("Pixel Digivolve", 1, 130)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(0, 66, 119));
        lblTitulo2.setText("BOTS");

        jLabel1.setFont(new java.awt.Font("Super Jello", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(92, 133, 146));
        jLabel1.setText("JUEGO EDUCATIVO • INFORMÁTICA ");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosL/robot (3).png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosL/bit.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTitulo)
                                .addGap(49, 49, 49)
                                .addComponent(lblTitulo1)
                                .addGap(43, 43, 43)
                                .addComponent(lblTitulo2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(panelAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(PanelRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(lblTitulo1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTitulo2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)))))
                .addGap(26, 26, 26)
                .addComponent(panelAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 237, Short.MAX_VALUE)
                .addComponent(PanelRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void configurarVentana() {
    setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    setLocationRelativeTo(null);

    getContentPane().setBackground(
            new java.awt.Color(248, 251, 253)
    );
}

private void configurarPaneles() {
    PanelSombra registro = (PanelSombra) PanelRegistrar;

    registro.setColorPanel(
            new java.awt.Color(199, 232, 253)
    );

    registro.setColorSombra(
            new java.awt.Color(0, 55, 93, 50)
    );

    registro.setColorBorde(
            new java.awt.Color(64, 160, 215, 55)
    );

    registro.setRedondez(40);
    registro.setTamañoSombra(16);
}

private void configurarComponentesFlatLaf() {
    EfectosLogin.aplicarCampoNombre(txfNombre);
    EfectosLogin.aplicarComboBox(cmbSeccion);
    EfectosLogin.aplicarBotonFlatLaf(btnComenzar);
    EfectosLogin.aplicarColoresTexto(txfNombre);

    lblTitulo.putClientProperty(
            "FlatLaf.style",
            "foreground:#004B7A"
    );

    lblRegistrate.putClientProperty(
            "FlatLaf.style",
            "foreground:#015689"
    );
}

private void cargarAvatar() {
    AvatarPanel avatar = new AvatarPanel();

    panelAvatar.setLayout(
            new java.awt.BorderLayout()
    );

    panelAvatar.add(
            avatar,
            java.awt.BorderLayout.CENTER
    );

    avatar.startAnimation();
}
    private void txfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNombreActionPerformed

    private void btnComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComenzarActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu(txfNombre.getText(), cmbSeccion.getSelectedItem().toString());
        menu.setVisible(true);
    }//GEN-LAST:event_btnComenzarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
        UIManager.setLookAndFeel(new FlatLightLaf());
        javax.swing.UIManager.put("Button.arc", 40);
        javax.swing.UIManager.put("Component.arc", 50);
        UIManager.put("TextComponent.arc", 20);
        UIManager.put("ScrollPane.arc", 20);
        javax.swing.UIManager.put("ComboBox.selectionArc", 20);

        javax.swing.UIManager.put(
                "Component.focusColor",
                new java.awt.Color(43, 164, 218)
        );

        javax.swing.UIManager.put(
                "Component.focusedBorderColor",
                new java.awt.Color(24, 141, 210)
        );
    
    } catch (Exception ex) {
        System.err.println("No se pudo iniciar el diseño");
    }
    
    

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelRegistrar;
    private javax.swing.JButton btnComenzar;
    private javax.swing.JComboBox<String> cmbSeccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRegistrate;
    private javax.swing.JLabel lblSeccion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JPanel panelAvatar;
    private javax.swing.JTextField txfNombre;
    // End of variables declaration//GEN-END:variables
}
