/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ResultadoQuizz;

import Login.FondoCircuitosPanel;

/**
 *
 * @author zoeca
 */
import Avatar.AvatarBitPanel;

public class Informatica extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Informatica.class.getName());

    /**
     * Creates new form Informatica
     */
    public Informatica() {
        setContentPane(new FondoCircuitosPanel());
        initComponents();
        
        PanelTituloPrincipal.setOpaque(false);
         setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        
        AvatarBitPanel bit = new AvatarBitPanel();
        bit.instalarEn(panelAvatarBit, 600, 600);
       bit.startAnimation();
       bit.saludar();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPorcentaje = new ResultadoQuizz.PanelTarjetaResultado();
        BarraPorcentaje = new ResultadoQuizz.BarraNivel();
        jLabel6 = new javax.swing.JLabel();
        PanelTResultado = new ResultadoQuizz.PanelTituloResultado();
        jLabel5 = new javax.swing.JLabel();
        PanelAprender = new ResultadoQuizz.PanelTarjetaResultado();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new ResultadoQuizz.SeparadorGlow();
        jPanel6 = new ResultadoQuizz.SeparadorGlow();
        jPanel7 = new ResultadoQuizz.SeparadorGlow();
        PanelTituloPrincipal = new ResultadoQuizz.PanelTituloPrincipal();
        jLabel1 = new ResultadoQuizz.LabelTitulo();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new ResultadoQuizz.LabelTitulo();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelAvatarBit = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPorcentaje.setBackground(new java.awt.Color(229, 244, 255));

        javax.swing.GroupLayout BarraPorcentajeLayout = new javax.swing.GroupLayout(BarraPorcentaje);
        BarraPorcentaje.setLayout(BarraPorcentajeLayout);
        BarraPorcentajeLayout.setHorizontalGroup(
            BarraPorcentajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
        );
        BarraPorcentajeLayout.setVerticalGroup(
            BarraPorcentajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Super Jello", 0, 32)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 40, 68));
        jLabel6.setText("Nivel Informático");

        javax.swing.GroupLayout PanelPorcentajeLayout = new javax.swing.GroupLayout(PanelPorcentaje);
        PanelPorcentaje.setLayout(PanelPorcentajeLayout);
        PanelPorcentajeLayout.setHorizontalGroup(
            PanelPorcentajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPorcentajeLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(PanelPorcentajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(BarraPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        PanelPorcentajeLayout.setVerticalGroup(
            PanelPorcentajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPorcentajeLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel6)
                .addGap(27, 27, 27)
                .addComponent(BarraPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        PanelTResultado.setBackground(new java.awt.Color(0, 40, 68));

        jLabel5.setFont(new java.awt.Font("Super Jello", 0, 34)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TU RESULTADO:");

        javax.swing.GroupLayout PanelTResultadoLayout = new javax.swing.GroupLayout(PanelTResultado);
        PanelTResultado.setLayout(PanelTResultadoLayout);
        PanelTResultadoLayout.setHorizontalGroup(
            PanelTResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTResultadoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelTResultadoLayout.setVerticalGroup(
            PanelTResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTResultadoLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(15, 15, 15))
        );

        PanelAprender.setBackground(new java.awt.Color(229, 244, 255));
        PanelAprender.setForeground(new java.awt.Color(0, 55, 93));
        PanelAprender.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Pixel Digivolve", 0, 38)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 40, 68));
        jLabel7.setText("En Informática puedes aprender");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosL/redess.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosL/progra.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosL/juegoo.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosL/desarrollo.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Super Jello", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 40, 68));
        jLabel12.setText("Programación");
        jLabel12.setToolTipText("");

        jLabel13.setFont(new java.awt.Font("Super Jello", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 40, 68));
        jLabel13.setText("Redes Informáticas");
        jLabel13.setToolTipText("");

        jLabel14.setFont(new java.awt.Font("Super Jello", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 40, 68));
        jLabel14.setText("Crear Juegos");
        jLabel14.setToolTipText("");

        jLabel15.setFont(new java.awt.Font("Super Jello", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 40, 68));
        jLabel15.setText("Diseñar Páginas Web");
        jLabel15.setToolTipText("");

        jPanel5.setBackground(new java.awt.Color(0, 66, 126));
        jPanel5.setForeground(new java.awt.Color(0, 66, 126));
        jPanel5.setPreferredSize(new java.awt.Dimension(6, 162));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(0, 66, 126));
        jPanel6.setForeground(new java.awt.Color(0, 66, 126));
        jPanel6.setPreferredSize(new java.awt.Dimension(6, 162));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(0, 66, 126));
        jPanel7.setForeground(new java.awt.Color(0, 66, 126));
        jPanel7.setPreferredSize(new java.awt.Dimension(6, 162));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelAprenderLayout = new javax.swing.GroupLayout(PanelAprender);
        PanelAprender.setLayout(PanelAprenderLayout);
        PanelAprenderLayout.setHorizontalGroup(
            PanelAprenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAprenderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelAprenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAprenderLayout.createSequentialGroup()
                        .addGroup(PanelAprenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12))
                        .addGap(30, 30, 30)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelAprenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAprenderLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel8))
                            .addGroup(PanelAprenderLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel13)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(PanelAprenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAprenderLayout.createSequentialGroup()
                                .addGroup(PanelAprenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel14))
                                .addGap(41, 41, 41)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel11)
                                .addGap(33, 33, 33))
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAprenderLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(85, 85, 85))))
        );
        PanelAprenderLayout.setVerticalGroup(
            PanelAprenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAprenderLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addGroup(PanelAprenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAprenderLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(PanelAprenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelAprenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(PanelAprenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)))
                    .addGroup(PanelAprenderLayout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addGroup(PanelAprenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)))
                    .addGroup(PanelAprenderLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(PanelAprenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Pixel Digivolve", 0, 90)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 110, 185));
        jLabel1.setText("Informática");
        jLabel1.setVerifyInputWhenFocusTarget(false);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosL/inform.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Super Jello", 0, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 25, 43));
        jLabel2.setText("TU CAMINO ES ");

        jLabel3.setFont(new java.awt.Font("Super Jello", 0, 55)); // NOI18N
        jLabel3.setText(" ¡");

        jLabel4.setFont(new java.awt.Font("Super Jello", 0, 55)); // NOI18N
        jLabel4.setText("!");

        javax.swing.GroupLayout PanelTituloPrincipalLayout = new javax.swing.GroupLayout(PanelTituloPrincipal);
        PanelTituloPrincipal.setLayout(PanelTituloPrincipalLayout);
        PanelTituloPrincipalLayout.setHorizontalGroup(
            PanelTituloPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTituloPrincipalLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(PanelTituloPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTituloPrincipalLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17))
                    .addGroup(PanelTituloPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );
        PanelTituloPrincipalLayout.setVerticalGroup(
            PanelTituloPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTituloPrincipalLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(PanelTituloPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTituloPrincipalLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel4))
                    .addGroup(PanelTituloPrincipalLayout.createSequentialGroup()
                        .addGroup(PanelTituloPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelTituloPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        panelAvatarBit.setBackground(new java.awt.Color(255, 255, 255));
        panelAvatarBit.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelAvatarBitLayout = new javax.swing.GroupLayout(panelAvatarBit);
        panelAvatarBit.setLayout(panelAvatarBitLayout);
        panelAvatarBitLayout.setHorizontalGroup(
            panelAvatarBitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );
        panelAvatarBitLayout.setVerticalGroup(
            panelAvatarBitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(PanelTituloPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(panelAvatarBit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelAprender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelPorcentaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelTResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelTResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PanelPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelTituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(PanelAprender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelAvatarBit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(263, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Informatica().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraPorcentaje;
    private javax.swing.JPanel PanelAprender;
    private javax.swing.JPanel PanelPorcentaje;
    private javax.swing.JPanel PanelTResultado;
    private javax.swing.JPanel PanelTituloPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel panelAvatarBit;
    // End of variables declaration//GEN-END:variables
}
