/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ResultadoQuizz;

/**
 *
 * @author zoeca
 */
public class Robotica extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Robotica.class.getName());

    /**
     * Creates new form Robotica
     */
    public Robotica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPorcentaje = new javax.swing.JPanel();
        BarraPorcentaje = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PanelTResultado = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PanelPorcentaje1 = new javax.swing.JPanel();
        BarraPorcentaje1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        PanelTResultado1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        PanelPorcentaje.setBackground(new java.awt.Color(229, 244, 255));

        javax.swing.GroupLayout BarraPorcentajeLayout = new javax.swing.GroupLayout(BarraPorcentaje);
        BarraPorcentaje.setLayout(BarraPorcentajeLayout);
        BarraPorcentajeLayout.setHorizontalGroup(
            BarraPorcentajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
        );
        BarraPorcentajeLayout.setVerticalGroup(
            BarraPorcentajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Super Jello", 0, 32)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 40, 68));
        jLabel6.setText("Nivel Informático");

        javax.swing.GroupLayout PanelPorcentajeLayout = new javax.swing.GroupLayout(PanelPorcentaje);
        PanelPorcentaje.setLayout(PanelPorcentajeLayout);
        PanelPorcentajeLayout.setHorizontalGroup(
            PanelPorcentajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPorcentajeLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(PanelPorcentajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(BarraPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPorcentajeLayout.setVerticalGroup(
            PanelPorcentajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPorcentajeLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel6)
                .addGap(27, 27, 27)
                .addComponent(BarraPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        PanelTResultado.setBackground(new java.awt.Color(0, 40, 68));

        jLabel5.setFont(new java.awt.Font("Super Jello", 0, 34)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TU RESULTADO:");

        javax.swing.GroupLayout PanelTResultadoLayout = new javax.swing.GroupLayout(PanelTResultado);
        PanelTResultado.setLayout(PanelTResultadoLayout);
        PanelTResultadoLayout.setHorizontalGroup(
            PanelTResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTResultadoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelTResultadoLayout.setVerticalGroup(
            PanelTResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTResultadoLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(15, 15, 15))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Pixel Digivolve", 0, 90)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 121, 115));
        jLabel1.setText("ROBÓTICA");
        jLabel1.setVerifyInputWhenFocusTarget(false);

        jLabel2.setFont(new java.awt.Font("Super Jello", 0, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 25, 43));
        jLabel2.setText("TU CAMINO ES ");

        jLabel3.setFont(new java.awt.Font("Super Jello", 0, 55)); // NOI18N
        jLabel3.setText(" ¡");

        jLabel4.setFont(new java.awt.Font("Super Jello", 0, 55)); // NOI18N
        jLabel4.setText("!");

        PanelPorcentaje1.setBackground(new java.awt.Color(229, 244, 255));

        javax.swing.GroupLayout BarraPorcentaje1Layout = new javax.swing.GroupLayout(BarraPorcentaje1);
        BarraPorcentaje1.setLayout(BarraPorcentaje1Layout);
        BarraPorcentaje1Layout.setHorizontalGroup(
            BarraPorcentaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
        );
        BarraPorcentaje1Layout.setVerticalGroup(
            BarraPorcentaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Super Jello", 0, 32)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 40, 68));
        jLabel7.setText("Nivel Robótico");

        javax.swing.GroupLayout PanelPorcentaje1Layout = new javax.swing.GroupLayout(PanelPorcentaje1);
        PanelPorcentaje1.setLayout(PanelPorcentaje1Layout);
        PanelPorcentaje1Layout.setHorizontalGroup(
            PanelPorcentaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPorcentaje1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(PanelPorcentaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(BarraPorcentaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPorcentaje1Layout.setVerticalGroup(
            PanelPorcentaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPorcentaje1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel7)
                .addGap(27, 27, 27)
                .addComponent(BarraPorcentaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        PanelTResultado1.setBackground(new java.awt.Color(0, 88, 84));

        jLabel8.setFont(new java.awt.Font("Super Jello", 0, 34)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TU RESULTADO:");

        javax.swing.GroupLayout PanelTResultado1Layout = new javax.swing.GroupLayout(PanelTResultado1);
        PanelTResultado1.setLayout(PanelTResultado1Layout);
        PanelTResultado1Layout.setHorizontalGroup(
            PanelTResultado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTResultado1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(515, Short.MAX_VALUE))
        );
        PanelTResultado1Layout.setVerticalGroup(
            PanelTResultado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTResultado1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelPorcentaje1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelTResultado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(PanelTResultado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PanelPorcentaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(594, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Robotica().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraPorcentaje;
    private javax.swing.JPanel BarraPorcentaje1;
    private javax.swing.JPanel PanelPorcentaje;
    private javax.swing.JPanel PanelPorcentaje1;
    private javax.swing.JPanel PanelTResultado;
    private javax.swing.JPanel PanelTResultado1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
