/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Quizz;
import Avatar.AvatarPanel;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author alvar
 */
public class Quizz_Vocacional extends javax.swing.JFrame {
private List<Preguntas> listaPreguntas = new ArrayList<>();
private int indiceActual = 0;
private int puntosInformatica = 0;
private int puntosRobotica = 0;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Quizz_Vocacional.class.getName());

    /**
     * Creates new form Quizz_Vocacional
     */
    public Quizz_Vocacional() {
        initComponents();
        cargarListaPreguntas();
        mostrarPreguntaActual();
        
        AvatarPanel avatar = new AvatarPanel();

        panelAvatar.setLayout(new BorderLayout());
        panelAvatar.add(avatar);

    avatar.startAnimation();
    }
private void cargarListaPreguntas() {
    // Pregunta 1
    listaPreguntas.add(new Preguntas(
        "¿Qué actividad te parece más interesante?",
        "Crear programas y aplicaciones.", "/img_quizz/informatica.png", "INFORMATICA",
        "Construir y programar robots.", "/img_quizz/robotica.png", "ROBOTICA"
    ));

    // Pregunta 2 (Puedes reutilizar fotos temporalmente si no tienes las nuevas)
    listaPreguntas.add(new Preguntas(
        "¿Qué herramienta prefieres dominar?",
        "Editores de código y bases de datos.", "/img_quizz/informatica.png", "INFORMATICA",
        "Circuitos, motores y sensores.", "/img_quizz/robotica.png", "ROBOTICA"
    ));

    // Pregunta 3
    listaPreguntas.add(new Preguntas(
        "¿Cuál de estos entornos te llama más la atención?",
        "Desarrollo Web y Apps Móviles.", "/img_quizz/informatica.png", "INFORMATICA",
        "Taller de Robótica y Mecatrónica.", "/img_quizz/robotica.png", "ROBOTICA"
    ));
}

private void mostrarPreguntaActual() {
    int totalPreguntas = listaPreguntas.size();

    if (indiceActual < totalPreguntas) {
        Preguntas p = listaPreguntas.get(indiceActual);

        // Actualizar barra y textos de la pregunta
        // NOTA: Reemplaza estos nombres por los nombres exactos de tus JLabels/JProgressBar
        lblPreguntaNumero.setText("Pregunta " + (indiceActual + 1) + " de " + totalPreguntas);
        jpbProgreso.setMinimum(0);
        jpbProgreso.setMaximum(totalPreguntas);
        jpbProgreso.setValue(indiceActual + 1);

        lbEnunciado.setText(p.getEnunciado());
        lblTextoIzquierda.setText(p.getTextoOpA());
        lbTextoDerecha.setText(p.getTextoOpB());

        // Actualizar imágenes
        try {
            lbImagenzquierda.setIcon(new ImageIcon(getClass().getResource(p.getRutaImgA())));
            lbImagenDerecha.setIcon(new ImageIcon(getClass().getResource(p.getRutaImgB())));
        } catch (Exception e) {
            System.out.println("Error al cargar imagen: " + e.getMessage());
        }

    } else {
        mostrarResultadoFinal();
    }
}

private void sumarPunto(String carrera) {
    if (carrera.equals("INFORMATICA")) {
        puntosInformatica++;
    } else if (carrera.equals("ROBOTICA")) {
        puntosRobotica++;
    }
}

private void siguientePregunta() {
    indiceActual++;
    mostrarPreguntaActual();
}

private void mostrarResultadoFinal() {
    String ganadora = (puntosInformatica >= puntosRobotica) ? "INFORMÁTICA" : "ROBÓTICA";
    
    JOptionPane.showMessageDialog(this, 
        "¡Quiz Finalizado con Éxito!\n\n" +
        "Puntos Informática: " + puntosInformatica + "\n" +
        "Puntos Robótica: " + puntosRobotica + "\n\n" +
        "Resultado Sugerido: " + ganadora,
        "Resultados Vocacionales",
        JOptionPane.INFORMATION_MESSAGE);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jpbProgreso = new javax.swing.JProgressBar();
        lblPreguntaNumero = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbEnunciado = new javax.swing.JLabel();
        jpInfor = new javax.swing.JPanel();
        lbImagenzquierda = new javax.swing.JLabel();
        jpRo = new javax.swing.JPanel();
        lbImagenDerecha = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblTextoIzquierda = new javax.swing.JLabel();
        lbTextoDerecha = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelAvatar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(235, 243, 250));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));

        jpbProgreso.setBackground(new java.awt.Color(204, 204, 255));
        jpbProgreso.setForeground(new java.awt.Color(153, 255, 153));
        jpbProgreso.setMaximum(15);

        lblPreguntaNumero.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblPreguntaNumero.setText("Pregunta 1 de 15");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cpu (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(250, 250, 250))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPreguntaNumero)
                        .addGap(37, 37, 37)))
                .addComponent(jpbProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(79, 79, 79))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPreguntaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpbProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbEnunciado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbEnunciado.setText("¿Qué actividad te parece más interesante?");

        jpInfor.setBackground(new java.awt.Color(255, 255, 255));
        jpInfor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));
        jpInfor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbImagenzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_quizz/informatica.png"))); // NOI18N
        lbImagenzquierda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbImagenzquierdaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpInforLayout = new javax.swing.GroupLayout(jpInfor);
        jpInfor.setLayout(jpInforLayout);
        jpInforLayout.setHorizontalGroup(
            jpInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInforLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbImagenzquierda)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jpInforLayout.setVerticalGroup(
            jpInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpInforLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbImagenzquierda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpRo.setBackground(new java.awt.Color(255, 255, 255));
        jpRo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));
        jpRo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbImagenDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_quizz/robotica.png"))); // NOI18N
        lbImagenDerecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbImagenDerechaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpRoLayout = new javax.swing.GroupLayout(jpRo);
        jpRo.setLayout(jpRoLayout);
        jpRoLayout.setHorizontalGroup(
            jpRoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpRoLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(lbImagenDerecha)
                .addGap(14, 14, 14))
        );
        jpRoLayout.setVerticalGroup(
            jpRoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbImagenDerecha)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/vs (1).png"))); // NOI18N

        jButton1.setText("jButton1");

        lblTextoIzquierda.setText("A). Reparar Computadoras");

        lbTextoDerecha.setText("B). Armar Robots");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(294, 294, 294))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(lbEnunciado))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jpInfor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel12)
                        .addGap(42, 42, 42)
                        .addComponent(jpRo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(lblTextoIzquierda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTextoDerecha)
                .addGap(184, 184, 184))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbEnunciado)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpInfor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpRo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTextoIzquierda)
                    .addComponent(lbTextoDerecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 28)); // NOI18N
        jLabel5.setText("QUIZZ VOCACIONAL");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("¿A qué carrera perteneces?");

        panelAvatar.setBackground(new java.awt.Color(255, 255, 255));
        panelAvatar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout panelAvatarLayout = new javax.swing.GroupLayout(panelAvatar);
        panelAvatar.setLayout(panelAvatarLayout);
        panelAvatarLayout.setHorizontalGroup(
            panelAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );
        panelAvatarLayout.setVerticalGroup(
            panelAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(416, 416, 416)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jLabel6)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(panelAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(219, 219, 219))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(193, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbImagenzquierdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbImagenzquierdaMouseClicked
        // TODO add your handling code here:
        sumarPunto(listaPreguntas.get(indiceActual).getCarreraA());
        siguientePregunta();
    }//GEN-LAST:event_lbImagenzquierdaMouseClicked

    private void lbImagenDerechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbImagenDerechaMouseClicked
        // TODO add your handling code here:
        sumarPunto(listaPreguntas.get(indiceActual).getCarreraB());
        siguientePregunta();
    }//GEN-LAST:event_lbImagenDerechaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Quizz_Vocacional().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jpInfor;
    private javax.swing.JPanel jpRo;
    private javax.swing.JProgressBar jpbProgreso;
    private javax.swing.JLabel lbEnunciado;
    private javax.swing.JLabel lbImagenDerecha;
    private javax.swing.JLabel lbImagenzquierda;
    private javax.swing.JLabel lbTextoDerecha;
    private javax.swing.JLabel lblPreguntaNumero;
    private javax.swing.JLabel lblTextoIzquierda;
    private javax.swing.JPanel panelAvatar;
    // End of variables declaration//GEN-END:variables
}
